### ISSUE TITLE
Didn't save patern path

### ISSUE THREAD

**Issue by dgoujard** [conveyal/gtfs-editor#169]
When i create an pattern and click on "Create alignement from Pattern" he didn't save the generated path. When i modify the path i got same errors : 

```
@6l7pmifp7
Internal Server Error (500) for request PUT /api/trippattern/8

Execution exception (In /app/utils/GeoUtils.java around line 81)
NoSuchFieldError occured : HTTP_URI_OGC

play.exceptions.JavaExecutionException: HTTP_URI_OGC
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.NoSuchFieldError: HTTP_URI_OGC
	at org.geotools.referencing.factory.HTTP_URI_AuthorityFactory.getAuthority(HTTP_URI_AuthorityFactory.java:77)
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.createFallbacks(ManyAuthoritiesFactory.java:167)
	at org.geotools.referencing.factory.ManyAuthoritiesFactory.<init>(ManyAuthoritiesFactory.java:125)
	at org.geotools.referencing.DefaultAuthorityFactory.getBackingFactory(DefaultAuthorityFactory.java:116)
	at org.geotools.referencing.DefaultAuthorityFactory.<init>(DefaultAuthorityFactory.java:69)
	at org.geotools.referencing.CRS.getAuthorityFactory(CRS.java:251)
	at utils.GeoUtils.getTransform(GeoUtils.java:81)
	at controllers.Api.updateTripPattern(Api.java:585)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
```

**Comment by dgoujard** [comment]
Resolved, it's caused by wrong install (dependencies). 
My install working install process is 
* Remove all jar in lib folder
* run play dependencies
* Download deleted jar from step 1
* Download this missings jar 
  - wget http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
  - wget http://dev.mapfish.org/maven/repository/voldemort/store/compress/h2-lzf/1.0/h2-lzf-1.0.jar
  - wget http://download.osgeo.org/webdav/geotools/java3d/vecmath/1.3.2/vecmath-1.3.2.jar
* Start the project with play run
