### ISSUE TITLE
Export to GTFS

### ISSUE THREAD

**Issue by dgoujard** [conveyal/gtfs-editor#171]
Hi, 

On my Digital Ocean VPS with 1Go of RAM when i tried to export on GTFS format i have an error OOP exeption.

I only have 3 StopPoints and one line.
```
@6l7pmifph
Internal Server Error (500) for request GET /export/creategtfs?calendarFrom=1424101516774&calendarTo=1426520716775&agencySelect=2

Execution exception (In /app/jobs/ProcessGtfsSnapshotExport.java around line 94)
OutOfMemoryError occured : Java heap space

play.exceptions.JavaExecutionException: Java heap space
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:237)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.mapdb.Caches$HashTable.<init>(Caches.java:209)
	at org.mapdb.DBMaker.extendCacheHashTable(DBMaker.java:873)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:738)
	at org.mapdb.DBMaker.make(DBMaker.java:665)
	at com.conveyal.gtfs.GTFSFeed.<init>(GTFSFeed.java:39)
	at jobs.ProcessGtfsSnapshotExport.doJob(ProcessGtfsSnapshotExport.java:94)
	at controllers.Application.createGtfs(Application.java:327)
	at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
	... 1 more
```

**Comment by mattwigway** [comment]
Hmm. Which commit of the editor are you using? We recently rewrote the entire export logic from scratch, and it should not require as much RAM anymore.

**Comment by mattwigway** [comment]
Postgres probably isn't great on RAM usage either. You might try adding some swap space.

**Comment by dgoujard** [comment]
I will try with an local VM with more ram but i already used gtfs-editor with VPS with 512Mo of ram few month ago (november).

**Comment by dgoujard** [comment]
Resolved, it's caused by wrong install (dependencies). 
My install working install process is 
* Remove all jar in lib folder
* run play dependencies
* Download deleted jar from step 1
* Download this missings jar 
  - wget http://download.osgeo.org/webdav/geotools/javax/media/jai_core/1.1.3/jai_core-1.1.3.jar
  - wget http://dev.mapfish.org/maven/repository/voldemort/store/compress/h2-lzf/1.0/h2-lzf-1.0.jar
  - wget http://download.osgeo.org/webdav/geotools/java3d/vecmath/1.3.2/vecmath-1.3.2.jar
* Start the project with play run
