### ISSUE TITLE
Compilation error at running time

### ISSUE THREAD

**Issue by nmaisonneuve** [conveyal/gtfs-editor#195]
I followed the installation instructions 
but when I launched the app,  I got : 

bjc[35439]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home//bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_20.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
CompilerOracle: exclude jregex/Pretokenizer.next
Listening for transport dt_socket at address: 8000
12:50:46,011 INFO  ~ Starting /Users/nico/Documents/dev/gtfs-editor
12:50:46,729 WARN  ~ You're running Play! in DEV mode
12:50:46,823 INFO  ~ Listening for HTTP on port 9000 (Waiting a first request to start) ...
12:50:57,914 ERROR ~

@6lcpi081d
Internal Server Error (500) for request GET /

Compilation error (In /app/controllers/api/CalendarController.java around line 77)
The file /app/controllers/api/CalendarController.java could not be compiled. Error raised is : The method apply(String) of type new Function&lt;String,ServiceCalendar.ServiceCalendarForPattern>(){} must override a superclass method

play.exceptions.CompilationException: The method apply(String) of type new Function<String,ServiceCalendar.ServiceCalendarForPattern>(){} must override a superclass method
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
	at play.Play.start(Play.java:516)
	at play.Play.detectChanges(Play.java:630)
	at play.Invoker$Invocation.init(Invoker.java:198)
	at Invocation.HTTP Request(Play!)

any help  / insight?

**Comment by mattwigway** [comment]
See information at #208; this is likely a java version issue.
