### ISSUE TITLE
Schedule page: cannot create frequency-based trips

### ISSUE THREAD

**Issue by markjd84** [conveyal/gtfs-editor#196]
Get the error message `Failed to create trip`.

Not sure if this is related to #167 

When I try to create from the schedule page I am watching the console output and it is giving: 

```
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "pattern" (class models.transit.Trip), not marked as ignorable (18 known properties: "agencyId", "tripShortName", "routeId", "blockId", "endTime", "patternId", "startTime", "headway", "useFrequency", "tripDescription", "tripDirection", "id", "tripHeadsign", "stopTimes" [truncated]])
 at [Source: {"useFrequency":true,"pattern":"62b2254b-13a8-4020-ada0-d1f41b78b5ef","tripDescription":"8 min","patternId":null,"calendarId":null,"startTime":null,"endTime":null,"headway":null}; line: 1, column: 33] (through reference chain: Trip["pattern"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
        at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:744)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:915)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1306)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1284)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:243)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
        at controllers.api.TripController.createTrip(TripController.java:73)

...
```

**Comment by markjd84** [comment]
Think this is a duplicate of #192 - can close on that basis?
