### ISSUE TITLE
GTFS import exception: Longitude out of range

### ISSUE THREAD

**Issue by thcrock** [conveyal/gtfs-editor#198]
I tried to load the Chicago GTFS feed using the latest master, and got this traceback:

...
23:16:18,297 INFO  ~ GtfsImporter: importing agencies...
23:16:18,317 INFO  ~ Agencies loaded: 1
23:16:18,317 INFO  ~ GtfsImporter: importing stops...
23:16:35,177 INFO  ~ Stops loaded: 0
23:16:35,177 INFO  ~ GtfsImporter: importing routes...
23:16:35,183 INFO  ~ Routes loaded:133
23:16:35,183 INFO  ~ GtfsImporter: importing Shapes...
23:16:37,983 INFO  ~ Shape points loaded: 400869
23:16:37,983 INFO  ~ Shapes loaded: 926
23:16:37,983 INFO  ~ GtfsImporter: importing Service Calendars...
23:16:37,992 INFO  ~ Service calendars loaded: 163
23:16:37,992 INFO  ~ GtfsImporter: importing trips...
23:16:40.095 INFO (GTFSFeed.java:189) Total patterns: 865
java.lang.IllegalArgumentException: Longitude �E is out of range (±180°).
        at org.geotools.referencing.GeodeticCalculator.checkLongitude(GeodeticCalculator.java:403)
        at org.geotools.referencing.GeodeticCalculator.setDestinationGeographicPoint(GeodeticCalculator.java:643)
        at models.transit.TripPattern.calcShapeDistTraveled(TripPattern.java:386)
        at jobs.ProcessGtfsSnapshotMerge.createTripPatternFromTrip(ProcessGtfsSnapshotMerge.java:476)
        at jobs.ProcessGtfsSnapshotMerge.run(ProcessGtfsSnapshotMerge.java:359)
        at controllers.Application.uploadGtfs(Application.java:402)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:251)
        at play.Invoker$Invocation.run(Invoker.java:278)
        at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:229)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

I've checked the two files with coordinates (shapes and stops) and didn't see any bad longitudes, so I'm not sure why this error is coming up.  In another issue thread, @mattwigway reported successfully running the importer on the CTA's feed using the new import code, so I'm not sure what changed.

CTA's feed: http://www.transitchicago.com/downloads/sch_data/

**Comment by zugaldia** [comment]
We're having the same error message with [this file](https://drive.google.com/open?id=0B_zq5oY3ar7GZmMzdnF6SFJETzg&authuser=0), and like @thcrock, we can't find any coordinates out of range.

We thought it could be bad CSV encoding (inadequately handed quotes or separators) that were confusing the reader but we can't find any instances of this either. We used the code on GitHub as of yesterday, the raw error we got is as follows:

```
20:15:14.298 INFO (Entity.java:232) Loading GTFS table feed_info from feed_info.txt
20:15:14.361 INFO (GTFSFeed.java:90) Feed ID is undefined.
20:15:14.362 INFO (GTFSFeed.java:92) Feed ID is 'null'.
20:15:14.362 INFO (Entity.java:232) Loading GTFS table agency from agency.txt
20:15:14.363 INFO (Entity.java:232) Loading GTFS table calendar from calendar.txt
20:15:14.365 INFO (Entity.java:232) Loading GTFS table calendar_dates from calendar_dates.txt
20:15:14.366 INFO (Entity.java:228) Table fare_attributes was missing but it is not required.
20:15:14.366 INFO (Entity.java:228) Table fare_rules was missing but it is not required.
20:15:14.367 INFO (Entity.java:232) Loading GTFS table routes from routes.txt
20:15:14.376 INFO (Entity.java:232) Loading GTFS table shapes from shapes.txt
20:15:15.329 INFO (Entity.java:232) Loading GTFS table stops from stops.txt
20:15:15.362 INFO (Entity.java:228) Table transfers was missing but it is not required.
20:15:15.363 INFO (Entity.java:232) Loading GTFS table trips from trips.txt
20:15:15.367 INFO (Entity.java:232) Loading GTFS table frequencies from frequencies.txt
20:15:15.384 INFO (Entity.java:232) Loading GTFS table stop_times from stop_times.txt
20:15:15.758 INFO (GTFSFeed.java:105) 0 errors
20:15:15,762 INFO  ~ GtfsImporter: importing agencies...
20:15:15,843 INFO  ~ Agencies loaded: 1
20:15:15,856 INFO  ~ GtfsImporter: importing stops...
20:15:17,100 INFO  ~ Stops loaded: 0
20:15:17,100 INFO  ~ GtfsImporter: importing routes...
20:15:17,123 INFO  ~ Routes loaded:134
20:15:17,123 INFO  ~ GtfsImporter: importing Shapes...
20:15:17,598 INFO  ~ Shape points loaded: 23098
20:15:17,598 INFO  ~ Shapes loaded: 134
20:15:17,598 INFO  ~ GtfsImporter: importing Service Calendars...
20:15:17,601 INFO  ~ Service calendars loaded: 4
20:15:17,601 INFO  ~ GtfsImporter: importing trips...
20:15:17.610 INFO (GTFSFeed.java:189) Total patterns: 268
20:15:17,860 INFO  ~ Fixed 8 / 13 stops after first round for trip pattern 42fb3690-d531-49e4-9feb-21fa2214553e (Bypass to Cabanas (13 stops)) on route 85bbcf2b-d0bb-4496-941d-577aebe82860
20:15:17,862 WARN  ~ Two stops on trip pattern 42fb3690-d531-49e4-9feb-21fa2214553e map to same point on shape
20:15:17,862 WARN  ~ Two stops on trip pattern 42fb3690-d531-49e4-9feb-21fa2214553e map to same point on shape
20:15:17,862 WARN  ~ Shape dist traveled past end of shape, was 26308.184541501345, expected max 26308.184541501345, clamping
20:15:18,197 INFO  ~ Fixed 23 / 26 stops after first round for trip pattern 6a124e93-c600-473e-a7e8-aae78fc71e8c (Kariobangi to Makadara/Mwisho (26 stops)) on route 71743dd5-09fd-4ae1-8ff8-b412fb46a8b3
20:15:18,283 INFO  ~ Fixed 5 / 7 stops after first round for trip pattern 857500cb-75af-4219-b598-8c6f28c84d9d (Highrise to Highrise (7 stops)) on route c4a6c95f-723c-48c9-bb72-920eede0b4ca
20:15:18,511 INFO  ~ Fixed 33 / 33 stops after first round for trip pattern b5f81a26-7e71-4763-87f7-6cd0fadeb900 (Pipeline Mombasa Road to Commercial (33 stops)) on route 27a376c3-8016-4052-a5e8-7702e4cc017d
20:15:18,543 INFO  ~ Fixed 7 / 9 stops after first round for trip pattern a38f1bd6-7271-400b-90da-ae21f96d8c5c (Gikomba to Gikomba (9 stops)) on route 0781c9b5-4f5f-4ab3-b7a9-551e32418e16
20:15:18,611 INFO  ~ Fixed 15 / 21 stops after first round for trip pattern e6cbd30f-2762-4361-b7a8-ab6e2e9913ba (Kenyatta University to KU (21 stops)) on route b52c2b43-77a7-45d3-a178-a6506a9fbb09
20:15:18,649 INFO  ~ Fixed 7 / 13 stops after first round for trip pattern 3b5b1a28-e3b0-4b49-a7a5-d704cbb7836d (Githurai to Gihurai (13 stops)) on route 87ae2be7-8c01-4a89-a29f-82d383f26a19
20:15:18,686 INFO  ~ Fixed 11 / 12 stops after first round for trip pattern 993547e8-d987-415a-ad27-e5bc4c3ad066 (Mukuru Kwa Njenga to Maziwa (12 stops)) on route 40b5e26a-867a-40d2-bb73-f37bb9198b61
20:15:18,787 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:18,886 INFO  ~ Fixed 24 / 27 stops after first round for trip pattern 61f40ae6-e022-47f2-b292-18fa8dd52fff (Saika to Tuskys Ronald Ngala (27 stops)) on route 27d58c83-0927-4128-8e84-c77e72e6043a
20:15:18,887 WARN  ~ Shape dist traveled past end of shape, was 29834.29079481281, expected max 29834.29079481281, clamping
20:15:19,203 INFO  ~ Fixed 29 / 42 stops after first round for trip pattern 729020a6-372b-410d-9f32-14b21d6ea9d4 (Wangige to Koja (42 stops)) on route f4f627ea-8989-4b0d-929b-79f00228d287
20:15:19,224 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:19,292 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:19,321 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:19,362 INFO  ~ Fixed 13 / 21 stops after first round for trip pattern 96c1ae3f-a995-48bb-92a3-960ba1883409 (Dandora to Gikomba (21 stops)) on route de74c0b7-b92d-423d-998b-168809350e00
20:15:19,786 INFO  ~ Fixed 22 / 33 stops after first round for trip pattern 1ab4eb35-f1f6-46ac-bf05-841a39bf93a8 (Ongata Rongai to Railways (33 stops)) on route 470fb568-b2a2-478d-a669-4536e91b772c
20:15:19,793 WARN  ~ Two stops on trip pattern 1ab4eb35-f1f6-46ac-bf05-841a39bf93a8 map to same point on shape
20:15:19,804 WARN  ~ Two stops on trip pattern 1ab4eb35-f1f6-46ac-bf05-841a39bf93a8 map to same point on shape
20:15:19,805 WARN  ~ Shape dist traveled past end of shape, was 37782.47968712481, expected max 37782.47968712481, clamping
20:15:19,806 WARN  ~ Shape dist traveled past end of shape, was 37782.47968712481, expected max 37782.47968712481, clamping
20:15:19,830 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:19,881 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:19,907 INFO  ~ Fixed 18 / 22 stops after first round for trip pattern 138c1594-3fcc-48d2-a65f-6fc2c914396d (Buruburu to Ambassadeur (22 stops)) on route d053fc4a-ac03-4793-8ecb-fa5b4da2e52e
20:15:19,908 WARN  ~ Two stops on trip pattern 138c1594-3fcc-48d2-a65f-6fc2c914396d map to same point on shape
20:15:19,908 WARN  ~ Two stops on trip pattern 138c1594-3fcc-48d2-a65f-6fc2c914396d map to same point on shape
20:15:19,909 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:19,914 INFO  ~ Fixed 4 / 5 stops after first round for trip pattern ca9af199-a0aa-437c-8acd-edd5bb9e3d39 (Nyayo to City Stadium/Lusaka Road Junctn (5 stops)) on route d19e671e-6340-411f-80be-46994083a0ca
20:15:19,940 INFO  ~ Fixed 13 / 27 stops after first round for trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 (Pipeline Jogoo road to Muthurwa (27 stops)) on route 00631eb3-7a77-4359-8caf-efa3267699fd
20:15:19,940 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,940 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,941 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,942 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,942 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,942 WARN  ~ Two stops on trip pattern 67661722-3a15-43ad-a2ec-860bf70255f0 map to same point on shape
20:15:19,942 WARN  ~ Shape dist traveled past end of shape, was 19017.264077759428, expected max 19017.264077759428, clamping
20:15:19,960 INFO  ~ Fixed 10 / 11 stops after first round for trip pattern 4e9195d7-ee48-4091-8ba5-df3d874d3bf8 (Imara Daima to Imara Daima (11 stops)) on route 3e778b30-b037-4f66-b5b3-784e8f7093bc
20:15:19,960 WARN  ~ Shape dist traveled past end of shape, was 22829.015061505113, expected max 22829.015061505113, clamping
20:15:20,083 INFO  ~ Fixed 51 / 62 stops after first round for trip pattern 5aa86c24-192c-43d3-836b-4847ef5604bc (Kiserian to Railways (62 stops)) on route e311bad2-09af-4e8a-ba7f-b6bc3ddbcada
20:15:20,085 WARN  ~ Shape dist traveled past end of shape, was 55404.6743767419, expected max 55404.6743767419, clamping
20:15:20,086 WARN  ~ Shape dist traveled past end of shape, was 55404.6743767419, expected max 55404.6743767419, clamping
20:15:20,104 INFO  ~ Fixed 6 / 13 stops after first round for trip pattern 941669e5-e250-4530-b675-7faf92aa44c3 (Ngumo to St.Peters Clavers Primary School/Salvation Army/Otc (13 stops)) on route 7167605e-c639-46d8-ad3c-b26cad839d67
20:15:20,106 WARN  ~ Shape dist traveled past end of shape, was 11158.71049589562, expected max 11158.71049589562, clamping
20:15:20,106 WARN  ~ Shape dist traveled past end of shape, was 11158.71049589562, expected max 11158.71049589562, clamping
20:15:20,121 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,128 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,142 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,170 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,191 INFO  ~ Fixed 12 / 18 stops after first round for trip pattern b5740723-3466-41d8-8ca6-829c4ef64ed0 (Jamhuri to Ambassadeur (18 stops)) on route f25ee018-e1ef-457d-b2d7-c561c068e5b8
20:15:20,191 WARN  ~ Shape dist traveled past end of shape, was 17711.982536665342, expected max 17711.982536665342, clamping
20:15:20,201 INFO  ~ Fixed 2 / 10 stops after first round for trip pattern a2ee90cf-0e91-4594-b071-3a28067d7afb (Ruiru to Super High Way (10 stops)) on route 2669decd-e5a2-4254-b63a-bfd8d39ebb26
20:15:20,201 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,201 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,202 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,202 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,202 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,202 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,202 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,202 WARN  ~ Shape dist traveled past end of shape, was 18104.104451285184, expected max 18104.104451285184, clamping
20:15:20,299 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,336 INFO  ~ Fixed 23 / 27 stops after first round for trip pattern e613ef51-ad05-469a-8ac9-a5fdb8f68dcd (Umoja to Innercore (27 stops)) on route 06fa2361-d69d-45d2-bda7-271abc3be709
20:15:20,347 INFO  ~ Fixed 5 / 10 stops after first round for trip pattern 78d07c89-094d-473e-928a-791c103e9ade (Highridge to Odeon (10 stops)) on route 95035b15-4d3a-476e-a808-09eb8c36dce4
20:15:20,347 WARN  ~ Shape dist traveled past end of shape, was 12100.460095416694, expected max 12100.460095416694, clamping
20:15:20,348 WARN  ~ Shape dist traveled past end of shape, was 12100.460095416694, expected max 12100.460095416694, clamping
20:15:20,348 WARN  ~ Shape dist traveled past end of shape, was 12100.460095416694, expected max 12100.460095416694, clamping
20:15:20,354 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,362 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,417 INFO  ~ Fixed 19 / 42 stops after first round for trip pattern 384b7ffb-3b6b-44fc-9501-e63ba37457ce (Wangige to Kenol Dagoretti Corner (42 stops)) on route ac4dd023-f601-4295-80ba-edf21ec54ead
20:15:20,420 WARN  ~ Shape dist traveled past end of shape, was 37750.05728405469, expected max 37750.05728405469, clamping
20:15:20,420 WARN  ~ Shape dist traveled past end of shape, was 37750.05728405469, expected max 37750.05728405469, clamping
20:15:20,680 INFO  ~ Fixed 20 / 30 stops after first round for trip pattern 54ef90fb-5d45-48b1-b62e-bbf0ab86caca (Kayole to Caltex (30 stops)) on route 93cc1c7c-3d41-4c2b-9e38-a267683a8723
20:15:20,681 WARN  ~ Shape dist traveled past end of shape, was 11861.551517994627, expected max 11861.551517994627, clamping
20:15:20,681 WARN  ~ Shape dist traveled past end of shape, was 11861.551517994627, expected max 11861.551517994627, clamping
20:15:20,682 WARN  ~ Shape dist traveled past end of shape, was 11861.551517994627, expected max 11861.551517994627, clamping
20:15:20,696 INFO  ~ Fixed 11 / 16 stops after first round for trip pattern cbbbb987-0663-418b-ac65-f0b2bf0f6aa2 (Rounder to Terminal Tusker (16 stops)) on route 26821f46-cc0b-402c-ae29-3ced9f67511f
20:15:20,697 WARN  ~ Shape dist traveled past end of shape, was 15381.46361153345, expected max 15381.46361153345, clamping
20:15:20,756 INFO  ~ Fixed 34 / 37 stops after first round for trip pattern ce665194-983f-4951-a4d7-f1c30b4d4fb4 (Athi River to Easy Coach/Uchumi (37 stops)) on route 4c0bd818-d543-42a7-96e3-179f9dab6ed4
20:15:20,756 WARN  ~ Shape dist traveled past end of shape, was 62264.125524481686, expected max 62264.125524481686, clamping
20:15:20,770 INFO  ~ Fixed 9 / 14 stops after first round for trip pattern 117c4348-9c9e-4737-ba52-9f7bbd3bd748 (Huruma to Terminal Tusker (14 stops)) on route b2100b16-0ef8-4463-9fdc-45e0020dfd49
20:15:20,770 WARN  ~ Shape dist traveled past end of shape, was 14146.552280166245, expected max 14146.552280166245, clamping
20:15:20,781 INFO  ~ Fixed 4 / 18 stops after first round for trip pattern fb8c067b-acaf-4766-9a01-b2dbc34fbb4f (Doni Carbanas to Doni (18 stops)) on route a23e4975-7427-474c-91c7-c09cd18dad76
20:15:20,781 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,782 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,782 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,782 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,782 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,783 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,783 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,783 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,783 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,783 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,783 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,784 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,784 WARN  ~ Shape dist traveled past end of shape, was 8917.043970762039, expected max 8917.043970762039, clamping
20:15:20,797 INFO  ~ Fixed 9 / 14 stops after first round for trip pattern ef0a5c15-aaaa-4459-aade-301d3d9807af (Kariobangi South to Terminal Otc (14 stops)) on route 88fb91c6-eb53-4849-bc32-8b79b35d944b
20:15:20,797 WARN  ~ Shape dist traveled past end of shape, was 15129.486916358022, expected max 15129.486916358022, clamping
20:15:20,798 WARN  ~ Shape dist traveled past end of shape, was 15129.486916358022, expected max 15129.486916358022, clamping
20:15:20,812 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,824 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,849 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,860 INFO  ~ Fixed 9 / 13 stops after first round for trip pattern b66e7539-b4a7-403e-a7c9-081829e97f2f (Dagoretti Market to Karen Shopping Centre/Karen (13 stops)) on route b5f121f0-de80-451f-928a-cb0197b0d1a4
20:15:20,872 INFO  ~ Fixed 8 / 12 stops after first round for trip pattern 083ee728-69de-4b40-8194-f9502d5a6241 (Imara Daima to Commercial Imara (12 stops)) on route 3e778b30-b037-4f66-b5b3-784e8f7093bc
20:15:20,873 WARN  ~ Shape dist traveled past end of shape, was 22829.015061505113, expected max 22829.015061505113, clamping
20:15:20,873 WARN  ~ Shape dist traveled past end of shape, was 22829.015061505113, expected max 22829.015061505113, clamping
20:15:20,897 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,928 INFO  ~ Fixed 8 / 23 stops after first round for trip pattern 32b017af-74ed-4475-929d-9b71f155c454 (Ruai to Rounder (23 stops)) on route c04d66d4-5272-43dc-93f8-ed61f55c1ecf
20:15:20,928 WARN  ~ Two stops on trip pattern 32b017af-74ed-4475-929d-9b71f155c454 map to same point on shape
20:15:20,937 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,945 INFO  ~ Fixed 1 / 8 stops after first round for trip pattern 84b10e3b-802b-4925-9c17-b02bfbd7ad8a (Maruirui to Maruirui (8 stops)) on route 0d7b43fa-ab9c-4851-a0a7-d14d9ee9a760
20:15:20,945 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,945 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,946 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,946 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,946 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,946 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,946 WARN  ~ Shape dist traveled past end of shape, was 6720.994044421104, expected max 6720.994044421104, clamping
20:15:20,976 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:20,996 INFO  ~ Fixed 9 / 18 stops after first round for trip pattern 664e08b5-5923-48e8-b28b-03c93c4731ef (Buruburu to Mutindwa (18 stops)) on route d053fc4a-ac03-4793-8ecb-fa5b4da2e52e
20:15:20,997 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:20,997 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:20,998 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:20,998 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:20,999 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:20,999 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:21,000 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:21,000 WARN  ~ Shape dist traveled past end of shape, was 16597.559046190258, expected max 16597.559046190258, clamping
20:15:21,048 INFO  ~ Fixed 26 / 27 stops after first round for trip pattern 3b55b688-528e-49b9-82e1-43d52edd7186 (Hardy to Karen (27 stops)) on route 389c81b0-15b6-41b3-888d-4e9f64412108
20:15:21,063 INFO  ~ Fixed 12 / 16 stops after first round for trip pattern 3e69ff0e-5a7e-41a2-a70b-1ac25d9f4564 (Komarocks to Umoja Stage (16 stops)) on route 47249637-e7f0-4b0e-9ffa-bb5e456a5bc6
20:15:21,068 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:21,083 INFO  ~ Fixed 13 / 14 stops after first round for trip pattern 05f40d66-4f07-4c3e-8da1-580e6abe6299 (Deep West/Moi Educational Centre to T-Mall (14 stops)) on route 94eadfa1-9644-4b7d-b59c-d16153a09d0a
20:15:21,091 INFO  ~ Fixed 5 / 6 stops after first round for trip pattern 8440d4ed-5b2d-4d87-adf1-2849e98313af (Kenyatta National Hospital to Kenyatta Hospital Stage (6 stops)) on route 76aa3402-2b3a-4816-8300-89ab444c2462
20:15:21,104 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:21,125 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:21,131 INFO  ~ Fixed 4 / 5 stops after first round for trip pattern 594ab2e8-c0ba-439a-80ee-6b097421e72c (Gikomba to Town (5 stops)) on route 481a0edb-2eac-47b1-a79e-b071a3c63d22
20:15:21,141 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:21,149 INFO  ~ Fixed 5 / 7 stops after first round for trip pattern 423369d6-967e-48be-b4d9-46eb5964c34e (Eastleigh to Joster (7 stops)) on route e94b6870-4a09-45ff-bd49-e286cb06cd8b
20:15:21,149 WARN  ~ Shape dist traveled past end of shape, was 2890.677676549826, expected max 2890.677676549826, clamping
20:15:21,149 WARN  ~ Shape dist traveled past end of shape, was 2890.677676549826, expected max 2890.677676549826, clamping
20:15:21,192 WARN  ~ Stop is more than 1km from its shape, using straight-line distances
20:15:21,230 INFO  ~ Fixed 19 / 30 stops after first round for trip pattern b30a4553-c17c-4f73-9a9d-e25df412b096 (Kahawa to Main Stage (30 stops)) on route b09122aa-9d47-44ab-bf39-bc4b7f1fd7f1
20:15:21,231 WARN  ~ Shape dist traveled past end of shape, was 34480.325194986835, expected max 34480.325194986835, clamping
20:15:21,245 INFO  ~ Fixed 7 / 14 stops after first round for trip pattern e62da8b9-5c47-4038-b2ed-9937ff21d3c8 (Gachie to Gasolina/Gichagi Mwisho (14 stops)) on route ea895909-ef57-4eed-bc04-cd1654f669ad
java.lang.IllegalArgumentException: Longitude �E is out of range (±180°).
        at org.geotools.referencing.GeodeticCalculator.checkLongitude(GeodeticCalculator.java:406)
        at org.geotools.referencing.GeodeticCalculator.setStartingGeographicPoint(GeodeticCalculator.java:549)
        at utils.GeoUtils.getCoordDistances(GeoUtils.java:53)
        at models.transit.TripPattern.calcShapeDistTraveled(TripPattern.java:446)
        at jobs.ProcessGtfsSnapshotMerge.createTripPatternFromTrip(ProcessGtfsSnapshotMerge.java:476)
        at jobs.ProcessGtfsSnapshotMerge.run(ProcessGtfsSnapshotMerge.java:359)
        at controllers.Application.uploadGtfs(Application.java:410)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:557)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:508)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:484)
        at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:479)
        at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
        at play.server.PlayHandler$NettyInvocation.execute(PlayHandler.java:251)
        at play.Invoker$Invocation.run(Invoker.java:278)
        at play.server.PlayHandler$NettyInvocation.run(PlayHandler.java:229)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```
Is there any way we could help troubleshoot this issue? Would the `gtfs-data-manager` be of help?
